// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildCommand(arg1:main.ScanRequest):Promise<Array<string>>;

export function CheckNmap():Promise<string>;

export function RunScan(arg1:main.ScanRequest):Promise<main.ScanResult>;
