// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildCommand(arg1) {
  return window['go']['main']['App']['BuildCommand'](arg1);
}

export function CheckNmap() {
  return window['go']['main']['App']['CheckNmap']();
}

export function RunScan(arg1) {
  return window['go']['main']['App']['RunScan'](arg1);
}
